name: Test Telegram Bot

on:
  workflow_dispatch:   # اجرا دستی فقط

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # نصب کتابخانه requests
      - run: pip install requests

      # اجرای فایل تست
      - name: Run test bot
        run: python scraper.py
